stages:
  data_ingestion:
    cmd: python src/IntelligentRadiologistAssistant/pipeline/stage_01_data_ingestion.py
    deps:
      - src/IntelligentRadiologistAssistant/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion
    


  training:
    cmd: python scr/IntelligentRadiologistAssistant/pipeline/stage_02_training.py
    deps:
      - scr/IntelligentRadiologistAssistant/pipeline/stage_02_training.py
      - config/config.yaml
      - artifacts/data_ingestion
    params:
      - IMAGE_SIZE
      - EPOCHS
    outs:
      - artifacts/runs
    
