artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://universe.roboflow.com/ds/wrkNC7zQLk?key=0wdzIbcOBR
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/data.yaml



prepare_model:

  root_dir: artifacts/prepare_model
  model_path: artifacts/prepare_model/model





training:
  root_dir: artifacts/training

 

  